//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsForYou.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyFeed
    {
        public int AgencyFeedId { get; set; }
        public string AgencyFeedUrl { get; set; }
        public int AgencyId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Category Category { get; set; }
    }
}
