//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUserManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocId { get; set; }
        public int ObjectId { get; set; }
        public int ObjectType { get; set; }
        public int DocType { get; set; }
        public string DocNameOnDisk { get; set; }
        public string DocOriginalName { get; set; }
        public System.DateTime Addedon { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual DocumentType DocumentType { get; set; }
    }
}
