//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUserManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteID { get; set; }
        public string NoteData { get; set; }
        public Nullable<int> UserID { get; set; }
        public string PageName { get; set; }
        public Nullable<System.DateTime> DateTimeAdded { get; set; }
    }
}
