//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoUserManagement.Web
{


    public partial class RegisterForm
    {

        /// <summary>
        /// NotesUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DemoUserManagement.Web.User_Control.NotesUserControl NotesUserControl;

        /// <summary>
        /// DocumentUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DemoUserManagement.Web.User_Control.DocumentUserControl DocumentUserControl;
    }
}
